# Generated by Django 4.0.6 on 2022-07-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='labels',
            new_name='label',
        ),
    ]
